all:
	@printf "\033[1;31mNothing to Make!\033[0m\n"
	
mingw:
	@printf "\033[1;31mNothing to Make!\033[0m\n"

install:
	@printf "\033[1;31mNoting to Install!\033[0m\n"

mingw_install:
	@printf "\033[1;31mNoting to Install!\033[0m\n"

clean:
	@printf "\033[1;31mNothing to Clean!\033[0m\n"

